#!/bin/bash
#sends an endless loop to all computers specified in machines
#messy, but works for now

for box in $(cat machines); do 
	ssh loud@${box} 'export DISPLAY=:0; while true; do sleep 3 ; firefox http://img.wonderhowto.com/img/47/58/63536789981803/0/hacking-and-you-various-shades-hackers.1280x600.jpg & done'
done
